#!/usr/bin/env nix-shell
#!nix-shell -i bash -p git nix
#!nix-shell --pure

set -e

REPO_ROOT=$(git rev-parse --show-toplevel)

mkdir -p "${REPO_ROOT}/.woodpecker"

echo "Creating formatting-check.yml..."
cat > "${REPO_ROOT}/.woodpecker/formatting-check.yml" << EOF
# This file is generated by code/generate-formatter-check.sh
# Do not edit it manually
steps:
  formatting-check:
    image: nixos/nix:latest
    environment:
      NIX_CONFIG: "experimental-features = nix-command flakes"
    commands:
      - nix build -L .#checks.x86_64-linux."formatting"

when:
  event:
    - pull_request
    - push
EOF

echo "✅ formatting-check.yml updated"
cat "${REPO_ROOT}/.woodpecker/formatting-check.yml"
